# This rule is not used by the project vault-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to auth.toolkit.vault.hopopops.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: auth-token-viewer-role
rules:
- apiGroups:
  - auth.toolkit.vault.hopopops.com
  resources:
  - tokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.toolkit.vault.hopopops.com
  resources:
  - tokens/status
  verbs:
  - get
