# This rule is not used by the project vault-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over auth.toolkit.vault.hopopops.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: auth-token-admin-role
rules:
- apiGroups:
  - auth.toolkit.vault.hopopops.com
  resources:
  - tokens
  verbs:
  - '*'
- apiGroups:
  - auth.toolkit.vault.hopopops.com
  resources:
  - tokens/status
  verbs:
  - get
