---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - auth.toolkit.vault.hopopops.com
  resources:
  - kubernetesroles
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.toolkit.vault.hopopops.com
  resources:
  - kubernetesroles/finalizers
  - tokens/finalizers
  verbs:
  - update
- apiGroups:
  - auth.toolkit.vault.hopopops.com
  resources:
  - kubernetesroles/status
  - tokens/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sys.toolkit.vault.hopopops.com
  resources:
  - auths
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sys.toolkit.vault.hopopops.com
  resources:
  - auths/finalizers
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - sys.toolkit.vault.hopopops.com
  resources:
  - auths/status
  - policies/status
  verbs:
  - get
  - patch
  - update
